name: Pull request checks

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ["16", "18", "20", "22"]
    steps:
      - uses: actions/checkout@v4

      - name: Install additional libraries
        uses: ./.github/actions/install-packages

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/eslint

  unit-tests:
    name: Unit Tests - Node.js v${{ matrix.node-version }}
    needs: [lint]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ["16", "18", "20", "22"]
    steps:
      - uses: actions/checkout@v4

      - name: Install additional libraries
        uses: ./.github/actions/install-packages

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/unit-tests
