name: Main branches push checks

on:
  push:
    branches:
      - 4-dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ./.github/actions/eslint

  unit-tests:
    name: Unit Tests - Node.js v${{ matrix.node-version }}
    needs: [lint]
    strategy:
      matrix:
        node-version: ['12.16.3', '12.20.0']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/unit-tests
